name: Backend Unit Tests

on:
  push:
    branches: [main, develop]
    paths:
      - 'backend/vizzy-backend/**'
  pull_request:
    branches: [main, develop]
    paths:
      - 'backend/vizzy-backend/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.x

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.npm
          **/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      working-directory: ./backend/vizzy-backend
      run: npm ci

    - name: Run tests
      working-directory: ./backend/vizzy-backend
      run: npm test
